"""
Single source of truth for all supported providers and their known models.
Exposed via GET /providers so the frontend can build dropdowns from this.
Every provider includes a "custom" option for models not in the list.
"""

PROVIDERS_REGISTRY = {
    "groq": {
        "label": "Groq",
        "base_url": "https://api.groq.com/openai/v1",
        "models": [
            "llama-3.1-8b-instant",
            "llama-3.3-70b-versatile",
            "llama-3.3-70b-specdec",
            "qwen/qwen3-32b",
            "qwen/qwen3.6-27b",
            "meta-llama/llama-4-scout-17b-16e-instruct",
            "openai/gpt-oss-120b",
            "openai/gpt-oss-20b",
            "mixtral-8x7b-32768",
            "gemma2-9b-it",
            "custom",
        ],
    },
    "openai": {
        "label": "OpenAI",
        "base_url": "https://api.openai.com/v1",
        "models": [
            "gpt-5",
            "gpt-5-mini",
            "gpt-5-nano",
            "gpt-5.1",
            "gpt-5.2",
            "gpt-5.4",
            "gpt-5.4-mini",
            "gpt-5.4-nano",
            "gpt-5.5",
            "gpt-5.6-sol",
            "gpt-5.6-terra",
            "gpt-5.6-luna",
            "gpt-4o",
            "gpt-4o-mini",
            "gpt-4.1",
            "gpt-4.1-mini",
            "gpt-4.1-nano",
            "o1",
            "o1-mini",
            "o3",
            "o3-mini",
            "o4-mini",
            "gpt-3.5-turbo",
            "custom",
        ],
    },
    "anthropic": {
        "label": "Anthropic",
        "base_url": "https://api.anthropic.com/v1",
        "models": [
            "claude-sonnet-5",
            "claude-sonnet-4-6",
            "claude-sonnet-4-5",
            "claude-haiku-4-5",
            "claude-opus-4-5",
            "claude-opus-4-6",
            "claude-opus-4-7",
            "claude-opus-4-8",
            "claude-3-5-sonnet-20241022",
            "claude-3-5-haiku-20241022",
            "claude-3-opus-20240229",
            "custom",
        ],
    },
    "gemini": {
        "label": "Google Gemini",
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai/",
        "models": [
            "gemini-3.5-flash",
            "gemini-3.1-pro-preview",
            "gemini-3.1-flash-lite",
            "gemini-3-flash-preview",
            "gemini-2.5-pro",
            "gemini-2.5-flash",
            "gemini-2.5-flash-lite",
            "gemini-2.0-flash",
            "gemini-1.5-pro",
            "custom",
        ],
    },
    "deepseek": {
        "label": "DeepSeek",
        "base_url": "https://api.deepseek.com/v1",
        "models": [
            "deepseek-v4-pro",
            "deepseek-v4-flash",
            "deepseek-v4",
            "deepseek-r1",
            "deepseek-chat",
            "deepseek-reasoner",
            "custom",
        ],
    },
    "perplexity": {
        "label": "Perplexity",
        "base_url": "https://api.perplexity.ai",
        "models": [
            "sonar",
            "sonar-pro",
            "sonar-reasoning",
            "sonar-reasoning-pro",
            "sonar-deep-research",
            "custom",
        ],
    },
    "mistral": {
        "label": "Mistral",
        "base_url": "https://api.mistral.ai/v1",
        "models": [
            "mistral-medium-3.5",
            "mistral-small-4",
            "mistral-large-3",
            "magistral-medium",
            "magistral-small",
            "devstral-2",
            "devstral-small-2",
            "codestral-latest",
            "ministral-3b",
            "ministral-8b",
            "ministral-14b",
            "mixtral-8x7b",
            "mixtral-8x22b",
            "custom",
        ],
    },
    "xai": {
        "label": "xAI",
        "base_url": "https://api.x.ai/v1",
        "models": [
            "grok-4.5",
            "grok-4.3",
            "grok-4.20-reasoning",
            "grok-4.20-non-reasoning",
            "grok-4",
            "grok-4-heavy",
            "custom",
        ],
    },
    "ollama": {
        "label": "Ollama (local)",
        "base_url": "http://localhost:11434",
        "models": [
            "llama3.3",
            "llama3.2",
            "qwen2.5-coder",
            "phi4",
            "mistral",
            "custom",
        ],
    },
}
